services:
  flask-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://man:27017

    depends_on:
      - man

  man:
    image : mongo:5.0
    ports:
      - "27017:27017"